// var fs = require('fs');
// string generated by canvas.toDataURL()
// var img = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0"
//     + "NAAAAKElEQVQ4jWNgYGD4Twzu6FhFFGYYNXDUwGFpIAk2E4dHDRw1cDgaCAASFOffhEIO"
//     + "3gAAAABJRU5ErkJggg==";
// strip off the data: url prefix to get just the base64-encoded bytes
// var data = img.replace(/^data:image\/\w+;base64,/, "");
// console.log()
// var buf = new Buffer(data, 'base64');
// fs.writeFileSync('image.png', buf);


// var cloudinary = require('cloudinary').v2
// cloudinary.config({
//     cloud_name: "dd0qluwmo",
//     api_key: "239791928262754",
//     api_secret: "WKb-pZdMnO3rSyH6bob9aRQj0fo"
// });
// console.time(`process`);
// cloudinary.uploader.upload("/home/rajat/imran/IMS/ims-node-server/images/abc1558633632.png",
//     function (error, result) {
//         console.timeEnd(`process`);
//         console.log(result, error)
//     });

async function helloWorld(){
    console.log('Hello World');
}

console.time('Execution Time : ');
helloWorld();
console.timeEnd('Execution Time : ');

output

Hello World
Execution Time : : 5.671ms


